export const metadata = {
  title: "Home | Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div className="bg-blue-500">Home</div>
    </>
  );
}
