import "./globals.css";
import { Suspense } from "react";
import LoadingPage from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <Suspense fallback={<LoadingPage />}>{children}</Suspense>
      </body>
    </html>
  );
}
